### ISSUE TITLE
quantile_tracks.sh:

### ISSUE THREAD

**Issue by alex-dem** [epigen/cll-chromatin#1]
Hello and thanks for uploading the whole code, making it so easy to follow the same steps and reproduce the results!

I am trying to run the quantile_tracks.sh but I have two problems:

1. The python script quantilize.py is missing and hence I am not able to run all the steps of the scripts

2. The file  /home/arendeiro/cll-patients/data/bamsizes.txt contains the size of the bam files or the RATIOS, i.e. for each bam file the number of total reads divided by the number of total reads for the smallest sample?

Thank you in advance for your time!

Alexandros

**Comment by afrendeiro** [comment]
Hi! Thanks for the interest.
The quantile tracks were a weak point in the code because the code was highly adapted to our computing environment.

Motivated by requests from other people I have made a description of this tracks here: [http://andre-rendeiro.com/2016/10/08/quantile_track](http://andre-rendeiro.com/2016/10/08/quantile_track) which includes the `quantilize.py` file you mention.

Let me know if this is enough to get you going.
Best, Andre

**Comment by alex-dem** [comment]
Andre thank you for the prompt response!

From a first look at your blog page, I think I have everything I need.

Thank you for your time and your great job,
Alexandros
